font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        13.0

background            #23262E
foreground            #D5CED9
selection_background  #3D4050
selection_foreground  #D5CED9
cursor                #00E8C6
cursor_text_color     #23262E

color0  #1C1E26
color8  #677691
color1  #EE5D43
color9  #EE5D43
color2  #A8FF60
color10 #A8FF60
color3  #FFE66D
color11 #FFE66D
color4  #91DDFF
color12 #91DDFF
color5  #B084EB
color13 #B084EB
color6  #00E8C6
color14 #00E8C6
color7  #D5CED9
color15 #FFFFFF

window_padding_width 14
hide_window_decorations yes
confirm_os_window_close 0

background_opacity 0.92
cursor_trail 3
cursor_trail_decay 0.1 0.4
cursor_blink_interval 0.5

tab_bar_edge top
tab_bar_style powerline
tab_powerline_style slanted
active_tab_background #00E8C6
active_tab_foreground #1C1E26
inactive_tab_background #23262E
inactive_tab_foreground #677691

disable_ligatures never
