#undef TAPPING_TERM
#define TAPPING_TERM 180

#define PERMISSIVE_HOLD

#define QUICK_TAP_TERM 0

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "l93Kz/orAEPP"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

