-- #######################################################################################
-- AUTOGENERATED HYPRLAND CONFIG.
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

-- This is an example Hyprland config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can split this configuration into multiple files
-- Create your files separately and then link them to this file like this:
-- source = ~/.config/hypr/myColors.conf

--###############
--## MONITORS ###
--###############

-- See https://wiki.hypr.land/Configuring/Monitors/

hl.monitor({
    output = "",
    mode = "preferred",
    position = "auto",
    scale = "auto",
})

-- nwg-displays writes saved monitor layout here
-- Source: ~/.config/hypr/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require(os.getenv("HOME") .. "/.config/hypr/monitors")

-- Per-OS fragment (dual-boot) → montressor/hypr/os-arch.conf | os-ubuntu.conf.
-- Distro/version-specific lines ($menu, hyprpm, 0.53-vs-0.55 shims) live there.
-- NOTE: the module is named "platform", NOT "os" — require("os") would return
-- Lua's built-in os stdlib from package.loaded and silently never read our file.
require(os.getenv("HOME") .. "/.config/hypr/platform")

--##################
--## MY PROGRAMS ###
--##################

-- See https://wiki.hypr.land/Configuring/Keywords/

-- Set programs that you use
local terminal = "kitty"
local fileManager = "dolphin"
-- $menu is per-OS (walker on Arch, rofi on Ubuntu) — defined in os.conf above

--################
--## AUTOSTART ###
--################

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:

-- Loads the passphrase-protected tower key into ssh-agent (rofi prompt, once per boot).
-- Without it waybar's tower modules can't authenticate and sit at "?".

--############################
--## ENVIRONMENT VARIABLES ###
--############################

-- See https://wiki.hypr.land/Configuring/Environment-variables/

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
hl.env("GTK_THEME", "adw-gtk3-dark")
hl.env("QT_QPA_PLATFORMTHEME", "gtk3")
hl.env("COLORTERM", "truecolor")
hl.env("PATH", "$HOME/.local/bin:$PATH")
-- waybar/popups are Hyprland children, not shell children — without this they can't
-- reach ssh-agent, and every tower module dies at "Permission denied (publickey)".
hl.env("SSH_AUTH_SOCK", "/run/user/1000/ssh-agent.socket")

-- DO NOT set AQ_DRM_DEVICES with NVIDIA first. This is a muxless Optimus laptop:
-- ALL display connectors (incl. the internal eDP panel) are wired to the Intel
-- iGPU; the NVIDIA 4060 has only the HDMI port. Making NVIDIA the primary scanout
-- GPU leaves Hyprland with zero monitors -> it dies on launch = login loop / black
-- screen (confirmed 2026-07-09). Hyprland MUST composite on Intel here. NVIDIA is
-- reachable per-app via PRIME offload (prime-run) for rendering only.

--##################
--## PERMISSIONS ###
--##################

-- See https://wiki.hypr.land/Configuring/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- ecosystem {
--   enforce_permissions = 1
-- }

-- permission = /usr/(bin|local/bin)/grim, screencopy, allow
-- permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
-- permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

--####################
--## LOOK AND FEEL ###
--####################

-- Refer to https://wiki.hypr.land/Configuring/Variables/

-- https://wiki.hypr.land/Configuring/Variables/#general

hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })
hl.animation({
    leaf = "global",
    enabled = true,
    speed = 10,
    bezier = "default",
})
hl.animation({
    leaf = "border",
    enabled = true,
    speed = 5.39,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "windows",
    enabled = true,
    speed = 4.79,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "windowsIn",
    enabled = true,
    speed = 4.1,
    bezier = "easeOutQuint",
    style = "popin 87%",
})
hl.animation({
    leaf = "windowsOut",
    enabled = true,
    speed = 1.49,
    bezier = "linear",
    style = "popin 87%",
})
hl.animation({
    leaf = "fadeIn",
    enabled = true,
    speed = 1.73,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeOut",
    enabled = true,
    speed = 1.46,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fade",
    enabled = true,
    speed = 3.03,
    bezier = "quick",
})
hl.animation({
    leaf = "layers",
    enabled = true,
    speed = 3.81,
    bezier = "easeOutQuint",
})
hl.animation({
    leaf = "layersIn",
    enabled = true,
    speed = 4,
    bezier = "easeOutQuint",
    style = "fade",
})
hl.animation({
    leaf = "layersOut",
    enabled = true,
    speed = 1.5,
    bezier = "linear",
    style = "fade",
})
hl.animation({
    leaf = "fadeLayersIn",
    enabled = true,
    speed = 1.79,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "fadeLayersOut",
    enabled = true,
    speed = 1.39,
    bezier = "almostLinear",
})
hl.animation({
    leaf = "workspaces",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesIn",
    enabled = true,
    speed = 1.21,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "workspacesOut",
    enabled = true,
    speed = 1.94,
    bezier = "almostLinear",
    style = "fade",
})
hl.animation({
    leaf = "zoomFactor",
    enabled = true,
    speed = 7,
    bezier = "quick",
})

hl.workspace_rule({
    workspace = "1",
    monitor = "eDP-1",
    default = true,
})

hl.workspace_rule({
    workspace = "2",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "3",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "4",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "5",
    monitor = "eDP-1",
})

hl.workspace_rule({
    workspace = "6",
    monitor = "HDMI-A-1",
    default = true,
})

hl.workspace_rule({
    workspace = "7",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "8",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "9",
    monitor = "HDMI-A-1",
})

hl.workspace_rule({
    workspace = "10",
    monitor = "HDMI-A-1",
})

hl.gesture({
    fingers = 3,
    direction = "horizontal",
    action = "workspace",
})
hl.gesture({
    fingers = 3,
    direction = "down",
    action = function()
        hl.exec_cmd(os.getenv("HOME") .. "/.local/bin/gesture-close-overlay.sh")
    end,
})

hl.device({
    name = "epic-mouse-v1",
    sensitivity = -0.5,
})

local mainMod = "SUPER" -- Sets "Windows" key as main modifier

hl.bind(mainMod .. " + Q", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + J", hl.dsp.exec_cmd("~/.local/bin/jarvis-live"))
hl.bind(mainMod .. " + SHIFT + Space", hl.dsp.exec_cmd("google-chrome-stable --profile-directory=Default --app-id=cadlkienfkclaiaibeoongdcgmdikeeg"))
hl.bind(mainMod .. " + period", hl.dsp.exec_cmd("~/.local/bin/spawn"))
hl.bind(mainMod .. " + P", hl.dsp.exec_cmd("~/.local/bin/project-picker"))
hl.bind(mainMod .. " + SHIFT + O", hl.dsp.exec_cmd("~/.local/bin/close"))
hl.bind(mainMod .. " + grave", hl.dsp.exec_cmd("hyprctl clients | grep -q 'title: Stopwatch' && hyprctl dispatch closewindow title:Stopwatch || kitty --title Stopwatch --override font_size=13 --override initial_window_width=310px --override initial_window_height=200px --override remember_window_size=no -e $HOME/.local/bin/stopwatch"))
hl.bind(mainMod .. " + C", hl.dsp.exec_cmd("~/.local/bin/smart-close.sh"))
hl.bind(mainMod .. " + SHIFT + C", hl.dsp.exec_cmd("~/.local/bin/kill-workspace.sh"))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd("~/.local/bin/music-launch.sh"))
hl.bind(mainMod .. " + SHIFT + Q", hl.dsp.exec_cmd("systemctl poweroff"))
hl.bind(mainMod .. " + Escape", hl.dsp.exec_cmd("systemctl suspend"))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + V", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mainMod .. " + SPACE", hl.dsp.exec_cmd("~/.local/bin/launcher"))
hl.bind(mainMod .. " + G", hl.dsp.exec_cmd("google-chrome-stable"))
hl.bind(mainMod .. " + SHIFT + ALT + P", hl.dsp.exec_cmd("firefox --private-window"))
hl.bind(mainMod .. " + A", hl.dsp.exec_cmd("/opt/google/chrome/google-chrome --profile-directory=Default --app-id=dfmohblocfmbgckfbldmimjbjomogdom"))
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd("$HOME/.local/bin/todoist-raise"))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd("$HOME/.local/bin/obsidian-raise"))
hl.bind(mainMod .. " + SHIFT + J", hl.dsp.exec_cmd("$HOME/.local/bin/jarvis-launcher"))
hl.bind(mainMod .. " + CTRL + J", hl.dsp.layout("togglesplit"))
hl.bind(mainMod .. " + SHIFT + Z", hl.dsp.exec_cmd("~/.local/bin/zoom-toggle.sh"))
hl.bind(mainMod .. " + K", hl.dsp.exec_cmd("/usr/bin/kodi"))
hl.bind(mainMod .. " + F", hl.dsp.exec_cmd("/usr/bin/delfin"))
hl.bind(mainMod .. " + SHIFT + F", hl.dsp.exec_cmd("/opt/google/chrome/google-chrome --profile-directory=Default --app=http://192.168.86.31:8096"))
hl.bind(mainMod .. " + SHIFT + A", hl.dsp.exec_cmd("$HOME/Applications/yaabsa/AppRun"))
hl.bind(mainMod .. " + SHIFT + M", hl.dsp.exec_cmd("/opt/google/chrome/google-chrome --profile-directory=Default --app-id=hpfldicfbfomlpcikngkocigghgafkph"))
hl.bind(mainMod .. " + L", hl.dsp.exec_cmd("/opt/google/chrome/google-chrome --profile-directory=Default --app=https://letterboxd.com"))
hl.bind(mainMod .. " + ALT + S", hl.dsp.exec_cmd("/opt/google/chrome/google-chrome --profile-directory=Default --app=https://www.serializd.com"))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd("/opt/google/chrome/google-chrome --profile-directory=Default --app=https://app.ynab.com"))
hl.bind(mainMod .. " + SHIFT + N", hl.dsp.exec_cmd("/opt/google/chrome/google-chrome --profile-directory=Default --app-id=eppojlglocelodeimnohnlnionkobfln"))
hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("/opt/google/chrome/google-chrome --profile-directory=Default --app=https://www.disneyplus.com"))
hl.bind(mainMod .. " + Y", hl.dsp.exec_cmd("/opt/google/chrome/google-chrome --profile-directory=Default --app=https://www.youtube.com"))
hl.bind(mainMod .. " + SHIFT + D", hl.dsp.exec_cmd("/usr/bin/discord"))
hl.bind(mainMod .. " + SHIFT + B", hl.dsp.exec_cmd("/usr/bin/bambu-studio"))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.exec_cmd("env QT_QPA_PLATFORM=xcb SDL_JOYSTICK_HIDAPI=0 pegasus-fe"))
hl.bind(mainMod .. " + ALT + G", hl.dsp.exec_cmd("/opt/google/chrome/google-chrome --profile-directory=Default --app-id=dadlbnbkdoflkdiglhklefcegfdnpgbj"))

hl.bind(mainMod .. " + slash", hl.dsp.exec_cmd("$HOME/.local/bin/moonkeys.py"))

hl.bind(mainMod .. " + left", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + right", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + up", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + down", hl.dsp.focus({ direction = "down" }))

hl.bind(mainMod .. " + SHIFT + left", hl.dsp.window.move({ direction = "l" }))
hl.bind(mainMod .. " + SHIFT + right", hl.dsp.window.move({ direction = "r" }))
hl.bind(mainMod .. " + SHIFT + up", hl.dsp.window.move({ direction = "u" }))
hl.bind(mainMod .. " + SHIFT + down", hl.dsp.window.move({ direction = "d" }))

hl.bind(mainMod .. " + ALT + left", hl.dsp.window.move({ workspace = "e-1" }))
hl.bind(mainMod .. " + ALT + right", hl.dsp.window.move({ workspace = "e+1" }))

hl.bind(mainMod .. " + 1", hl.dsp.focus({ workspace = 1 }))
hl.bind(mainMod .. " + 2", hl.dsp.focus({ workspace = 2 }))
hl.bind(mainMod .. " + 3", hl.dsp.focus({ workspace = 3 }))
hl.bind(mainMod .. " + 4", hl.dsp.focus({ workspace = 4 }))
hl.bind(mainMod .. " + 5", hl.dsp.focus({ workspace = 5 }))
hl.bind(mainMod .. " + 6", hl.dsp.focus({ workspace = 6 }))
hl.bind(mainMod .. " + 7", hl.dsp.focus({ workspace = 7 }))
hl.bind(mainMod .. " + 8", hl.dsp.focus({ workspace = 8 }))
hl.bind(mainMod .. " + 9", hl.dsp.focus({ workspace = 9 }))
hl.bind(mainMod .. " + 0", hl.dsp.focus({ workspace = 10 }))

hl.bind(mainMod .. " + SHIFT + 1", hl.dsp.window.move({ workspace = 1, follow = false }))
hl.bind(mainMod .. " + SHIFT + 2", hl.dsp.window.move({ workspace = 2, follow = false }))
hl.bind(mainMod .. " + SHIFT + 3", hl.dsp.window.move({ workspace = 3, follow = false }))
hl.bind(mainMod .. " + SHIFT + 4", hl.dsp.window.move({ workspace = 4, follow = false }))
hl.bind(mainMod .. " + SHIFT + 5", hl.dsp.window.move({ workspace = 5, follow = false }))
hl.bind(mainMod .. " + SHIFT + 6", hl.dsp.window.move({ workspace = 6, follow = false }))
hl.bind(mainMod .. " + SHIFT + 7", hl.dsp.window.move({ workspace = 7, follow = false }))
hl.bind(mainMod .. " + SHIFT + 8", hl.dsp.window.move({ workspace = 8, follow = false }))
hl.bind(mainMod .. " + SHIFT + 9", hl.dsp.window.move({ workspace = 9, follow = false }))
hl.bind(mainMod .. " + SHIFT + 0", hl.dsp.window.move({ workspace = 10, follow = false }))

hl.bind(mainMod .. " + ALT + W", hl.dsp.exec_cmd("~/.config/waybar/workspace-popup.py"))

hl.bind(mainMod .. " + SHIFT + W", hl.dsp.exec_cmd("pkill waybar; sleep 1; waybar"))

hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag())
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize())

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("swayosd-client --output-volume raise"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("swayosd-client --output-volume lower"), { locked = true, repeating = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("swayosd-client --output-volume mute-toggle"), { locked = true, repeating = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd("swayosd-client --input-volume mute-toggle"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

hl.bind("Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\" - | swappy -f -"))
hl.bind(mainMod .. " + Print", hl.dsp.exec_cmd("grim - | swappy -f -"))

-- hyprexpo plugin config removed in the Lua port — the plugin is not installed
-- and its bind is commented out. Re-add via hl.plugin.hyprexpo({...}) if ever enabled.

hl.window_rule({
    name = "suppress-maximize-events",
    match = {
        class = ".*",
    },
    -- Ignore maximize requests from all apps. You'll probably like this.
    suppress_event = "maximize",
})

hl.window_rule({
    name = "fix-xwayland-drags",
    match = {
        class = "^$",
        title = "^$",
        xwayland = true,
        float = true,
        fullscreen = false,
        pin = false,
    },
    -- Fix some dragging issues with XWayland
    no_focus = true,
})

hl.window_rule({
    name = "move-hyprland-run",
    match = {
        class = "hyprland-run",
    },
    move = "20 monitor_h-120",
    float = true,
})

hl.window_rule({
    name = "mtga-fullscreen",
    match = {
        class = "^(mtga.exe)$",
    },
    monitor = "HDMI-A-1",
    fullscreen = true,
})

hl.window_rule({
    name = "pavucontrol-position",
    match = {
        class = "^(pavucontrol)$",
    },
    float = true,
    size = "460 300",
    move = "100%-462 40",
})

hl.window_rule({
    name = "songsterr-dark-border",
    match = {
        class = "^(crx_dadlbnbkdoflkdiglhklefcegfdnpgbj)$",
    },
    border_color = "rgb(1C1E26) rgb(1C1E26)",
})

hl.window_rule({
    name = "stopwatch-popup",
    match = {
        title = "Stopwatch",
    },
    float = true,
    pin = true,
    size = "310 200",
    move = "100%-320 48",
})

hl.window_rule({
    name = "agent-jarvis-border",
    match = {
        title = ".*Jarvis · System.*",
    },
    border_color = "rgb(00E8C6) rgb(00E8C6)",
})

hl.window_rule({
    name = "jarvis-live-border",
    match = {
        class = "^(jarvis-live)$",
    },
    border_color = "rgb(00E8C6) rgb(00E8C6)",
})

hl.window_rule({
    name = "jarvis-connected-border",
    match = {
        class = "^(jarvis-connected)$",
    },
    border_color = "rgb(B084EB) rgb(B084EB)",
})

hl.window_rule({
    name = "jarvis-launcher",
    match = {
        class = "^(io\\.jarvis\\.Launcher)$",
    },
    float = true,
    size = "780 540",
    center = true,
    border_color = "rgb(00E8C6) rgb(00E8C6)",
})

hl.window_rule({
    name = "jarvis-custom-border",
    match = {
        class = "^(jarvis-custom)$",
    },
    border_color = "rgb(FFE66D) rgb(FFE66D)",
})

hl.config({
    general = {
        gaps_in = 5,
        gaps_out = 12,
        border_size = 2,
        col = {
            active_border = { colors = { "rgba(00E8C6ee)", "rgba(B084EBee)" }, angle = 45 },
            inactive_border = "rgba(1C1E26aa)",
        },
        resize_on_border = true,
        -- Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
        allow_tearing = false,
        layout = "dwindle",
    },
    -- https://wiki.hypr.land/Configuring/Variables/#decoration
    decoration = {
        rounding = 10,
        rounding_power = 2,
        -- Change transparency of focused and unfocused windows
        active_opacity = 1.0,
        inactive_opacity = 1.0,
        shadow = {
            enabled = true,
            range = 20,
            render_power = 3,
            color = "rgba(00E8C614)",
        },
        blur = {
            enabled = true,
            size = 6,
            passes = 3,
            vibrancy = 0.1696,
        },
    },
    -- https://wiki.hypr.land/Configuring/Variables/#animations
    animations = {
        enabled = true, -- was hyprlang's joke value "yes, please :)"; Lua requires a real bool
        -- Default curves, see https://wiki.hypr.land/Configuring/Animations/#curves
        --        NAME,           X0,   Y0,   X1,   Y1
        -- Default animations, see https://wiki.hypr.land/Configuring/Animations/
        --           NAME,          ONOFF, SPEED, CURVE,        [STYLE]
    },
    -- Ref https://wiki.hypr.land/Configuring/Workspace-Rules/
    -- "Smart gaps" / "No gaps when only"
    -- uncomment all if you wish to use that.
    -- workspace = w[tv1], gapsout:0, gapsin:0
    -- workspace = f[1], gapsout:0, gapsin:0
    -- Bind workspaces to monitors — laptop 1-5, ultrawide (HDMI-A-1) 6-10
    -- windowrule {
    --     name = no-gaps-wtv1
    --     match:float = false
    --     match:workspace = w[tv1]
    --
    --     border_size = 0
    --     rounding = 0
    -- }
    --
    -- windowrule {
    --     name = no-gaps-f1
    --     match:float = false
    --     match:workspace = f[1]
    --
    --     border_size = 0
    --     rounding = 0
    -- }
    -- See https://wiki.hypr.land/Configuring/Dwindle-Layout/ for more
    dwindle = {
        preserve_split = true, -- You probably want this
    },
    -- See https://wiki.hypr.land/Configuring/Master-Layout/ for more
    master = {
        new_status = "master",
    },
    -- https://wiki.hypr.land/Configuring/Variables/#misc
    misc = {
        force_default_wallpaper = 0,
        disable_hyprland_logo = true,
    },
    --############
    --## INPUT ###
    --############
    -- https://wiki.hypr.land/Configuring/Variables/#input
    input = {
        kb_layout = "us",
        kb_variant = "",
        kb_model = "",
        kb_options = "caps:escape",
        kb_rules = "",
        follow_mouse = 1,
        sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.
        touchpad = {
            natural_scroll = true,
        },
    },
    -- See https://wiki.hypr.land/Configuring/Gestures
    -- gesture = 3, up, hyprexpo:expo, toggle  # uncomment after: hyprpm add https://github.com/hyprwm/hyprland-plugins && hyprpm install hyprexpo
    -- Example per-device config
    -- See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more
    --##################
    --## KEYBINDINGS ###
    --##################
    -- See https://wiki.hypr.land/Configuring/Keywords/
    -- Example binds, see https://wiki.hypr.land/Configuring/Binds/ for more
    -- Move focus with mainMod + arrow keys
    -- Move active window within layout with mainMod + SHIFT + arrow keys
    -- Move active window to prev/next existing workspace (incl. named launch workspaces)
    -- Switch workspaces with mainMod + [0-9]
    -- Move active window to a workspace with mainMod + SHIFT + [0-9] (per-monitor)
    -- Workspace settings popup (renumber / move to monitor)
    -- Restart waybar
    -- Scroll through existing workspaces with mainMod + scroll
    -- Move/resize windows with mainMod + LMB/RMB and dragging
    -- Laptop multimedia keys for volume and LCD brightness
    -- Requires playerctl
    -- Screenshots
    --#############################
    --## WINDOWS AND WORKSPACES ###
    --#############################
    -- See https://wiki.hypr.land/Configuring/Window-Rules/ for more
    -- See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules
    -- Example windowrules that are useful
    -- Hyprland-run windowrule
    -- Jarvis terminal border color — title is set by ~/.local/bin/jarvis (the only agent)
    -- via OSC 2 and locked with `kitten @ set-window-title` (see _agent-theme.sh).
    -- Format: "<symbol> <Name> · <Subtitle>"  →  match on the unique name.
    -- Jarvis Live — kitty with class jarvis-live, tiles normally.
    -- Jarvis Connected — the org/connected MCP door. Purple border to read apart.
    -- Jarvis Launcher — the Super+Shift+J picker (GTK4, app id io.jarvis.Launcher).
    -- Floats centered; cyan glow to match the accent it launches.
    -- Jarvis Custom — a picker-composed instance. Yellow border: hand-mixed toolset.
})

hl.on("hyprland.start", function()
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("/usr/bin/gnome-keyring-daemon --start --components=secrets")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    hl.exec_cmd("ssh-agent-load")
    hl.exec_cmd("waybar")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("swaync")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("swayosd-server")
    hl.exec_cmd("udiskie --no-tray --automount --notify")
end)

