-- Per-OS Hyprland fragment — CachyOS/Arch side.
-- Symlinked to ~/.config/hypr/os.conf by bootstrap-linux.sh; Ubuntu's twin is
-- os-ubuntu.conf. ONLY distro- or version-specific config lives here —
-- everything shared stays in hyprland.conf (one file, both OSes).

-- App launcher (walker-bin from CachyOS repos/AUR; elephant backend via
-- systemd user unit)
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local menu = "walker"

-- hyprpm plugins need headers matching the running hyprland — Arch-only flow

-- Obsidian autostart, minimized: lives hidden on its own special workspace so
-- Obsidian Sync keeps propagating vault edits in the background (it's the sole
-- off-machine backup for vault-based configs). Show/hide with Super+O.
-- Arch-only until Obsidian is installed on the Ubuntu side (then mirror to os-ubuntu.conf).
-- NO blanket class windowrule here: it would also swallow Settings / second-vault
-- windows opened later, making them invisible until the Super+N toggle dragged
-- them back. The dispatcher prefix below parks only the autostart window.

hl.on("hyprland.start", function()
    hl.exec_cmd("hyprpm reload -n")
    hl.exec_cmd("obsidian", { workspace = "special:obsidian silent" })
end)

